training_pipeline_config:
  pipeline_name: thyroid
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/imkushwaha/Thyroid-Disease-Detection/main/Training_FileFromDB/InputFile.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  schema_dir : config
  schema_file : schema.yaml
  report_page_file_name : report.html
