grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      max_depth: 2
    search_param_grid:
      max_depth:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 15
      - 20
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 2
    search_param_grid:
      max_depth:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 15
      - 20

  module_3:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      max_depth: 2
    search_param_grid:
      max_depth:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 15
      - 20

  module_4:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 50
    search_param_grid:
      n_estimators:
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100  